function [trialsNames, trialsMatrix]=GoNogo_Auditory_Phase(S,PhaseName)

switch PhaseName
	case 'Pavlovian' 
        trialsNames={'Cue A Go','Cue B NoGo',...
            'blank','blank','blank','blank'};
        trialsMatrix=[...
        %  1.type, 2.proba, 3.sound, 4.LickTimer,       5.LickValve,      6.NaN  7. marker       8.noLickTimer     9.noLickValve
            1,      1,          1,    S.Reward,         S.GUI.RewardValve, NaN,  double('o'),    S.Reward,         S.GUI.RewardValve;...   
            2,      0,          2,    S.GUI.PunishTime, S.GUI.PunishValve, NaN,  double('v'),    S.Reward,         S.GUI.RewardValve;...   
            3,      0,          3,    S.Reward,         S.GUI.RewardValve, NaN,  double('o'),    S.GUI.PunishTime, S.GUI.PunishValve;...   
            4,      0,          4,    S.GUI.PunishTime, S.GUI.PunishValve, NaN,  double('v'),    S.Reward,         S.GUI.RewardValve;...
            ];
            
    case 'NoPunishment' 
        trialsNames={'Cue A Go','Cue B NoGo',...
            'blank','blank','blank','blank'};
        trialsMatrix=[...
        %  1.type, 2.proba, 3.sound, 4.LickTimer,       5.LickValve,     6.NaN   7.marker        8.noLickTimer     9.noLickValve
            1,      0.8,        1,    S.Reward,         S.GUI.RewardValve,  NaN, double('o'),    S.Reward,         S.GUI.OmissionValve;...   
            2,      0.2,        2,    S.GUI.PunishTime, S.GUI.OmissionValve,NaN, double('v'),    S.GUI.PunishTime, S.GUI.OmissionValve;...   
            3,      0,          3,    S.Reward,         S.GUI.RewardValve,  NaN, double('o'),    S.Reward,         S.GUI.OmissionValve;...   
            4,      0,          4,    S.GUI.PunishTime, S.GUI.PunishValve,  NaN, double('v'),    S.GUI.PunishTime, S.GUI.OmissionValve;... 
            ];
        
    case '2Tones' 
        trialsNames={'Cue A Go','Cue B NoGo',...
            'blank','blank','blank','blank'};
        trialsMatrix=[...
        %  1.type, 2.proba, 3.sound, 4.LickTimer,       5.LickValve,      6.NaN  7.marker        8.noLickTimer     9.noLickValve
            1,      0.5,        1,    S.Reward,         S.GUI.RewardValve,  NaN, double('o')     S.Reward,         S.GUI.OmissionValve;...   
            2,      0.5,        2,    S.GUI.PunishTime, S.GUI.PunishValve,  NaN, double('v'),    S.GUI.PunishTime, S.GUI.OmissionValve;...   
            3,      0,          3,    S.Reward,         S.GUI.RewardValve,  NaN, double('o'),    S.Reward,         S.GUI.OmissionValve;...   
            4,      0,          4,    S.GUI.PunishTime, S.GUI.PunishValve,  NaN, double('v'),    S.GUI.PunishTime, S.GUI.OmissionValve;...
            ];
        
    case '4Tones' 
        trialsNames={'Cue A Go','Cue B Nogo',...
            'Cue C Go','Cue D Nogo',...
            'blank','blank'};
        trialsMatrix=[...
        %  1.type, 2.proba, 3.sound, 4.LickTimer,       5.LickValve,                            8.noLickTimer       9.noLickValve
            1,      0.25,        1,    S.Reward,         S.GUI.RewardValve,  NaN, double('o'),   S.Reward,          S.GUI.OmissionValve;...   
            2,      0.25,        2,    S.GUI.PunishTime, S.GUI.PunishValve,  NaN, double('v'),   S.GUI.PunishTime,  S.GUI.OmissionValve;...   
            3,      0.25,        3,    S.Reward,         S.GUI.RewardValve,  NaN, double('o'),   S.Reward,          S.GUI.OmissionValve;...   
            4,      0.25,        4,    S.GUI.PunishTime, S.GUI.PunishValve,  NaN, double('v'),   S.GUI.PunishTime,  S.GUI.OmissionValve;...
            ];
        
end     
end

  
