function [trialsNames, trialsMatrix, ezTrialsSeq]=StateUncertainty_Phase(S,PhaseName)

switch PhaseName
   
    case 'BeliefState'  % training
        trialsNames={'CueA Reward','CueA Omission',...
                     'CueB Reward','CueB Omission',...
                     'CueC Reward','CueC Omission',...
                     'CueD Reward','CueD Omission',...
                     'Uncued Reward','Uncued Omission', ...
                     'OptoStim at CueA','OptoStim at CueB',...
                     'OptoStim at CueC','OptoStim at CueD',...
                     'OptoStim at CueA Outcome','OptoStim at CueB Outcome',...
                     'OptoStim at CueC Outcome','OptoStim at CueD Outcome'};
                 
         
                 
%        trialsMatrix=[...
% %         1.type, 2.proba,                  3.sound, 4.delay,   5.valve,
% %         6.Outcome      7.Marker        8. OptoStimCue  9. Delay
% %         OptoStimCue 10.OptoStimRwd  11. Reward Duration
%             1,	S.GUI.ProbA,                1,  S.GUI.DelayA,	S.GUI.RewardValveA,     S.RewA,     double('o'),    0,  S.GUI.OptoStimCueDelay,	0 , S.GUI.OrderA;...   % CueA: reward trial
%             2,	S.GUI.ProbAOmission,        1,  S.GUI.DelayA,	S.GUI.OmissionValve,	S.RewA,     double('o'),    0,	S.GUI.OptoStimCueDelay,	0 , S.GUI.OrderAOmission;...   % CueA: omission
%             3,  S.GUI.ProbB,                2,  S.GUI.DelayB,   S.GUI.RewardValveB,     S.RewB,     double('s'),    0,  S.GUI.OptoStimCueDelay, 0 , S.GUI.OrderB ;...
%             4,  S.GUI.ProbBOmission,        2,  S.GUI.DelayB,   S.GUI.OmissionValve,    S.RewB,     double('s'),    0,  S.GUI.OptoStimCueDelay, 0 , S.GUI.OrderBOmission;...
%             5,  S.GUI.ProbC,                3,  S.GUI.DelayC,   S.GUI.RewardValveC,     S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay, 0 , S.GUI.OrderC ;...   
%             6,  S.GUI.ProbCOmission,        3,  S.GUI.DelayC,   S.GUI.OmissionValve,    S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay, 0 , S.GUI.OrderCOmission ;...
%             7,  S.GUI.ProbD,                4,  S.GUI.DelayD,   S.GUI.RewardValveD,     S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay, 0 , S.GUI.OrderD ;...   
%             8,  S.GUI.ProbDOmission,        4,  S.GUI.DelayD,   S.GUI.OmissionValve,    S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay, 0 , S.GUI.OrderDOmission ;...
%             9,  S.GUI.ProbUncuedRwd,        4,  S.GUI.DelayA,   S.GUI.RewardValveA,     S.RewA,     double('o'),    0,  S.GUI.OptoStimCueDelay, 0 , S.GUI.OrderUncuedRwd ;...   % Uncued reward
%             10, S.GUI.ProbUncuedOmission,   4,  S.GUI.DelayA,   S.GUI.OmissionValve,    S.RewA,     double('o'),    0,  S.GUI.OptoStimCueDelay, 0 , S.GUI.OrderUncuedOmission;...   % No Cue + no reward
%             11, S.GUI.ProbAOptoCue,         1,  S.GUI.DelayA,   S.GUI.RewardValveA,     S.RewA,     double('o'),    2,  S.GUI.OptoStimCueDelay, 0 , S.GUI.OrderAOptoCue;....   % (CueA+ Stim) + reward 
%             12, S.GUI.ProbBOptoCue,         2,  S.GUI.DelayB,   S.GUI.RewardValveB,     S.RewB,     double('s'),    2,  S.GUI.OptoStimCueDelay, 0 , S.GUI.OrderBOptoCue;...
%             13, S.GUI.ProbCOptoCue,         3,  S.GUI.DelayC,   S.GUI.RewardValveC,     S.RewC,     double('x'),    2,  S.GUI.OptoStimCueDelay, 0 , S.GUI.OrderCOptoCue;...
%             14, S.GUI.ProbDOptoCue,         4,  S.GUI.DelayD,   S.GUI.RewardValveD,     S.RewD,     double('x'),    2,  S.GUI.OptoStimCueDelay, 0 , S.GUI.OrderDOptoCue;...
%             15, S.GUI.ProbAOptoOutcome,     1,  S.GUI.DelayA,   S.GUI.RewardValveA,     S.RewA,     double('o'),    0,  S.GUI.OptoStimCueDelay, 2 , S.GUI.OrderAOptoOutcome;...   %  CueA  + (reward + stim)
%             16, S.GUI.ProbBOptoOutcome,     2,  S.GUI.DelayB,   S.GUI.RewardValveB,     S.RewB,     double('s'),    0,  S.GUI.OptoStimCueDelay, 2 , S.GUI.OrderBOptoOutcome;...
%             17, S.GUI.ProbCOptoOutcome,     3,  S.GUI.DelayC,   S.GUI.RewardValveC,     S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay, 2 , S.GUI.OrderCOptoOutcome ;
%             18, S.GUI.ProbDOptoOutcome,     4,  S.GUI.DelayD,   S.GUI.RewardValveD,     S.RewD,     double('x'),    0,  S.GUI.OptoStimCueDelay, 2 , S.GUI.OrderDOptoOutcome ];

       trialsMatrix=[...
%         1.type, 2.proba,                  3.sound, 4.delay,   5.valve,
%         6.Outcome      7.Marker        8. OptoStimCue  9. Delay
%         OptoStimCue 10.OptoStimRwd  11. Reward Duration
            1,	S.GUI.ProbA,                1,  1,	 S.GUI.RewardValveA,     S.RewA,     double('o'),    0,  S.GUI.OptoStimCueDelay,	0 , S.GUI.OrderA;...   % CueA: reward trial
            2,	S.GUI.ProbAOmission,        1,  1,	 S.GUI.OmissionValve,    S.RewA,     double('o'),    0,	 S.GUI.OptoStimCueDelay,	0 , S.GUI.OrderAOmission;...   % CueA: omission
            3,  S.GUI.ProbB,                2,  2,   S.GUI.RewardValveB,     S.RewB,     double('s'),    0,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderB ;...
            4,  S.GUI.ProbBOmission,        2,  2,   S.GUI.OmissionValve,    S.RewB,     double('s'),    0,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderBOmission;...
            5,  S.GUI.ProbC,                3,  3,   S.GUI.RewardValveC,     S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderC ;...   
            6,  S.GUI.ProbCOmission,        3,  3,   S.GUI.OmissionValve,    S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderCOmission ;...
            7,  S.GUI.ProbD,                4,  4,   S.GUI.RewardValveD,     S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderD ;...   
            8,  S.GUI.ProbDOmission,        4,  4,   S.GUI.OmissionValve,    S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderDOmission ;...
            9,  S.GUI.ProbUncuedRwd,        4,  1,   S.GUI.RewardValveA,     S.RewA,     double('o'),    0,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderUncuedRwd ;...   % Uncued reward
            10, S.GUI.ProbUncuedOmission,   4,  1,   S.GUI.OmissionValve,    S.RewA,     double('o'),    0,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderUncuedOmission;...   % No Cue + no reward
            11, S.GUI.ProbAOptoCue,         1,  1,   S.GUI.RewardValveA,     S.RewA,     double('o'),    2,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderAOptoCue;....   % (CueA+ Stim) + reward 
            12, S.GUI.ProbBOptoCue,         2,  2,   S.GUI.RewardValveB,     S.RewB,     double('s'),    2,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderBOptoCue;...
            13, S.GUI.ProbCOptoCue,         3,  3,   S.GUI.RewardValveC,     S.RewC,     double('x'),    2,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderCOptoCue;...
            14, S.GUI.ProbDOptoCue,         4,  4,   S.GUI.RewardValveD,     S.RewD,     double('x'),    2,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderDOptoCue;...
            15, S.GUI.ProbAOptoOutcome,     1,  1,   S.GUI.RewardValveA,     S.RewA,     double('o'),    0,  S.GUI.OptoStimCueDelay,    2 , S.GUI.OrderAOptoOutcome;...   %  CueA  + (reward + stim)
            16, S.GUI.ProbBOptoOutcome,     2,  2,   S.GUI.RewardValveB,     S.RewB,     double('s'),    0,  S.GUI.OptoStimCueDelay,    2 , S.GUI.OrderBOptoOutcome;...
            17, S.GUI.ProbCOptoOutcome,     3,  3,   S.GUI.RewardValveC,     S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay,    2 , S.GUI.OrderCOptoOutcome ;
            18, S.GUI.ProbDOptoOutcome,     4,  4,   S.GUI.RewardValveD,     S.RewD,     double('x'),    0,  S.GUI.OptoStimCueDelay,    2 , S.GUI.OrderDOptoOutcome ];


end


