function [trialsNames, trialsMatrix]=BeliefState_Phase(S,PhaseName)

switch PhaseName
   
    case 'BeliefState'  % training
        trialsNames={'CueA Reward','CueA Omission',...
                     'CueB Reward','CueB Omission',...
                     'CueC Reward','CueC Omission',...
                     'CueD Reward','CueD Omission',...
                     'Uncued Reward','Uncued Omission', ...
                     'OptoStim at CueA','OptoStim at CueB',...
                     'OptoStim at CueC','OptoStim at CueD',...
                     'OptoStim at CueA Outcome','OptoStim at CueB Outcome',...
                     'OptoStim at CueC Outcome','OptoStim at CueD Outcome'};

       trialsMatrix=[...
%         1.type, 2.proba,                  3.sound, 4.delay,   5.valve,
%         6.Outcome      7.Marker        8. OptoStimCue  9. Delay
%         OptoStimCue 10.OptoStimRwd  11. Reward Duration
            1,	S.GUI.ProbA.A,                1,  1,	 S.GUI.RewardValveA,        S.RewA,     double('o'),    0,  S.GUI.OptoStimCueDelay,     0 , S.GUI.OrderA.A;...   % CueA: reward trial
            2,	S.GUI.ProbA.AOmission,        1,  1,	 S.GUI.OmissionValve,       S.RewA,     double('o'),    0,	 S.GUI.OptoStimCueDelay,	0 , S.GUI.OrderA.AOmission;...   % CueA: omission
            3,  S.GUI.ProbB.B,                2,  2,   S.GUI.RewardValveB,          S.RewB,     double('s'),    0,  S.GUI.OptoStimCueDelay,     0 , S.GUI.OrderB.B ;...
            4,  S.GUI.ProbB.BOmission,        2,  2,   S.GUI.OmissionValve,         S.RewB,     double('s'),    0,  S.GUI.OptoStimCueDelay,     0 , S.GUI.OrderB.BOmission;...
            5,  S.GUI.ProbC.C,                3,  3,   S.GUI.RewardValveC,          S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay,     0 , S.GUI.OrderC.C ;...   
            6,  S.GUI.ProbC.COmission,        3,  3,   S.GUI.OmissionValve,         S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay,     0 , S.GUI.OrderC.COmission ;...
            7,  S.GUI.ProbD.D,                4,  4,   S.GUI.RewardValveD,          S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay,     0 , S.GUI.OrderD.D ;...   
            8,  S.GUI.ProbD.DOmission,        4,  4,   S.GUI.OmissionValve,         S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderD.DOmission ;...
            9,  S.GUI.ProbUncued.UncuedRwd,        4,  1,   S.GUI.RewardValveA,     S.RewA,     double('o'),    0,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderUncued.UncuedRwd ;...   % Uncued reward
            10, S.GUI.ProbUncued.UncuedOmission,   4,  1,   S.GUI.OmissionValve,    S.RewA,     double('o'),    0,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderUncued.UncuedOmission;...   % No Cue + no reward
            11, S.GUI.ProbA.AOptoCue,         1,  1,   S.GUI.RewardValveA,          S.RewA,     double('o'),    2,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderA.AOptoCue;....   % (CueA+ Stim) + reward 
            12, S.GUI.ProbB.BOptoCue,         2,  2,   S.GUI.RewardValveB,          S.RewB,     double('s'),    2,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderB.BOptoCue;...
            13, S.GUI.ProbC.COptoCue,         3,  3,   S.GUI.RewardValveC,          S.RewC,     double('x'),    2,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderC.COptoCue;...
            14, S.GUI.ProbD.DOptoCue,         4,  4,   S.GUI.RewardValveD,          S.RewD,     double('x'),    2,  S.GUI.OptoStimCueDelay,    0 , S.GUI.OrderD.DOptoCue;...
            15, S.GUI.ProbA.AOptoOutcome,     1,  1,   S.GUI.RewardValveA,          S.RewA,     double('o'),    0,  S.GUI.OptoStimCueDelay,    2 , S.GUI.OrderA.AOptoOutcome;...   %  CueA  + (reward + stim)
            16, S.GUI.ProbB.BOptoOutcome,     2,  2,   S.GUI.RewardValveB,          S.RewB,     double('s'),    0,  S.GUI.OptoStimCueDelay,    2 , S.GUI.OrderB.BOptoOutcome;...
            17, S.GUI.ProbC.COptoOutcome,     3,  3,   S.GUI.RewardValveC,          S.RewC,     double('x'),    0,  S.GUI.OptoStimCueDelay,    2 , S.GUI.OrderC.COptoOutcome ;
            18, S.GUI.ProbD.DOptoOutcome,     4,  4,   S.GUI.RewardValveD,          S.RewD,     double('x'),    0,  S.GUI.OptoStimCueDelay,    2 , S.GUI.OrderD.DOptoOutcome ];


end


